name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日 00:00（UTC）执行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: 检查出你的 Fork 仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: 配置 Git 用户信息
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: 添加 AList 上游仓库
        run: |
          git remote add upstream https://github.com/alist-org/alist.git || true
          git fetch upstream
          git merge upstream/main --no-edit
          git push origin main

      - name: 触发 Build Workflow
        run: |
          gh workflow run build.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
